### ISSUE TITLE
github CI job 'trigger' should not run on forks

### ISSUE THREAD

**Issue by axel-h** [seL4/projects_libs#16]
It's basically the same problem as in https://github.com/seL4/seL4_projects_libs/issues/33, the github CI job 'trigger' should not run on forks, as this fails when updating `master` there. Updating `master` on forks is necessary when testing PR on forks using the github CI action. Getting an error after the update everytime is a bit annoying.

**Comment by Ivan-Velickovic** [comment]
With https://github.com/seL4/ci-actions/pull/210 this can be closed now.
